/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesoDenegadoRouteImport } from './routes/acceso-denegado'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartaRouteImport } from './routes/carta'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PedidoRouteImport } from './routes/pedido'
import { Route as ProveedorRouteImport } from './routes/proveedor'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as PedidoConfirmacionRouteImport } from './routes/pedido_.confirmacion'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoDenegadoRoute = AccesoDenegadoRouteImport.update({
  id: '/acceso-denegado',
  path: '/acceso-denegado',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaRoute = CartaRouteImport.update({
  id: '/carta',
  path: '/carta',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoRoute = PedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedorRoute = ProveedorRouteImport.update({
  id: '/proveedor',
  path: '/proveedor',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoConfirmacionRoute = PedidoConfirmacionRouteImport.update({
  id: '/pedido_/confirmacion',
  path: '/pedido/confirmacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso-denegado': typeof AccesoDenegadoRoute
  '/admin': typeof AdminRoute
  '/carta': typeof CartaRoute
  '/equipo': typeof EquipoRoute
  '/login': typeof LoginRoute
  '/pedido': typeof PedidoRoute
  '/proveedor': typeof ProveedorRoute
  '/reservar': typeof ReservarRoute
  '/pedido/confirmacion': typeof PedidoConfirmacionRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso-denegado': typeof AccesoDenegadoRoute
  '/admin': typeof AdminRoute
  '/carta': typeof CartaRoute
  '/equipo': typeof EquipoRoute
  '/login': typeof LoginRoute
  '/pedido': typeof PedidoRoute
  '/proveedor': typeof ProveedorRoute
  '/reservar': typeof ReservarRoute
  '/pedido/confirmacion': typeof PedidoConfirmacionRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceso-denegado': typeof AccesoDenegadoRoute
  '/admin': typeof AdminRoute
  '/carta': typeof CartaRoute
  '/equipo': typeof EquipoRoute
  '/login': typeof LoginRoute
  '/pedido': typeof PedidoRoute
  '/proveedor': typeof ProveedorRoute
  '/reservar': typeof ReservarRoute
  '/pedido_/confirmacion': typeof PedidoConfirmacionRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso-denegado'
    | '/admin'
    | '/carta'
    | '/equipo'
    | '/login'
    | '/pedido'
    | '/proveedor'
    | '/reservar'
    | '/pedido/confirmacion'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso-denegado'
    | '/admin'
    | '/carta'
    | '/equipo'
    | '/login'
    | '/pedido'
    | '/proveedor'
    | '/reservar'
    | '/pedido/confirmacion'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/acceso-denegado'
    | '/admin'
    | '/carta'
    | '/equipo'
    | '/login'
    | '/pedido'
    | '/proveedor'
    | '/reservar'
    | '/pedido_/confirmacion'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoDenegadoRoute: typeof AccesoDenegadoRoute
  AdminRoute: typeof AdminRoute
  CartaRoute: typeof CartaRoute
  EquipoRoute: typeof EquipoRoute
  LoginRoute: typeof LoginRoute
  PedidoRoute: typeof PedidoRoute
  ProveedorRoute: typeof ProveedorRoute
  ReservarRoute: typeof ReservarRoute
  PedidoConfirmacionRoute: typeof PedidoConfirmacionRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso-denegado': {
      id: '/acceso-denegado'
      path: '/acceso-denegado'
      fullPath: '/acceso-denegado'
      preLoaderRoute: typeof AccesoDenegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carta': {
      id: '/carta'
      path: '/carta'
      fullPath: '/carta'
      preLoaderRoute: typeof CartaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido': {
      id: '/pedido'
      path: '/pedido'
      fullPath: '/pedido'
      preLoaderRoute: typeof PedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedor': {
      id: '/proveedor'
      path: '/proveedor'
      fullPath: '/proveedor'
      preLoaderRoute: typeof ProveedorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido_/confirmacion': {
      id: '/pedido_/confirmacion'
      path: '/pedido/confirmacion'
      fullPath: '/pedido/confirmacion'
      preLoaderRoute: typeof PedidoConfirmacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoDenegadoRoute: AccesoDenegadoRoute,
  AdminRoute: AdminRoute,
  CartaRoute: CartaRoute,
  EquipoRoute: EquipoRoute,
  LoginRoute: LoginRoute,
  PedidoRoute: PedidoRoute,
  ProveedorRoute: ProveedorRoute,
  ReservarRoute: ReservarRoute,
  PedidoConfirmacionRoute: PedidoConfirmacionRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
