// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hibjyholvvxdastnttob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpYmp5aG9sdnZ4ZGFzdG50dG9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgyNzM2NDksImV4cCI6MjEwMzg0OTY0OX0.S8giXU4cSfg-EMj5BnXomBbRap-1ZQBYhDUqgJoP7VY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});